{% set name = "vgi" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('VERSION_FROM_GIT_TAG') }}

source:
  git_url: https://github.com/cvxgrp/vgi

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.8
    - numpy >=1.17.5
    - scipy
    - cvxpy
    - cvxpygen
    - scikit-learn
    - pathos

  run:
    - pip
    - python >=3.8
    - numpy >=1.17.5
    - scipy
    - cvxpy
    - cvxpygen
    - scikit-learn
    - pathos

about:
  home: https://github.com/cvxgrp/vgi
  license: APACHEv2
  license_family: Apache
  license_file:
  summary: A method for convex stocastic control.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Alan Yang
